export const disciplines = [
  { id: "pendidikan", name: "Pendidikan", mono: "PD", docCount: 218400 },
  { id: "teknik", name: "Teknik", mono: "TK", docCount: 341200 },
  { id: "bisnis", name: "Bisnis & Manajemen", mono: "BM", docCount: 176900 },
  { id: "hukum", name: "Hukum", mono: "HK", docCount: 98300 },
  { id: "kesehatan", name: "Kesehatan", mono: "KS", docCount: 154700 },
  { id: "desain", name: "Desain", mono: "DS", docCount: 41200 },
  { id: "komunikasi", name: "Ilmu Komunikasi", mono: "IK", docCount: 63800 },
  { id: "komputer", name: "Ilmu Komputer", mono: "IC", docCount: 289500 },
  { id: "pertanian", name: "Pertanian", mono: "PT", docCount: 87600 },
  { id: "arsitektur", name: "Arsitektur", mono: "AR", docCount: 52100 },
];

export const universities = [
  { id: "ui", name: "Universitas Indonesia", abbr: "UI", province: "Jawa Barat", indexedDocs: 812400, status: "Terverifikasi", topFaculties: ["Ilmu Komputer", "Kedokteran", "Ekonomi & Bisnis"] },
  { id: "ugm", name: "Universitas Gadjah Mada", abbr: "UGM", province: "D.I. Yogyakarta", indexedDocs: 764100, status: "Terverifikasi", topFaculties: ["Teknik", "Pertanian", "Hukum"] },
  { id: "itb", name: "Institut Teknologi Bandung", abbr: "ITB", province: "Jawa Barat", indexedDocs: 598700, status: "Terverifikasi", topFaculties: ["Teknik Sipil", "Informatika", "Desain"] },
  { id: "ipb", name: "IPB University", abbr: "IPB", province: "Jawa Barat", indexedDocs: 412300, status: "Terverifikasi", topFaculties: ["Pertanian", "Kehutanan", "Teknologi Pangan"] },
  { id: "unpad", name: "Universitas Padjadjaran", abbr: "UNPAD", province: "Jawa Barat", indexedDocs: 387900, status: "Terverifikasi", topFaculties: ["Hukum", "Kedokteran", "Komunikasi"] },
  { id: "unair", name: "Universitas Airlangga", abbr: "UNAIR", province: "Jawa Timur", indexedDocs: 356200, status: "Terverifikasi", topFaculties: ["Kedokteran", "Kesehatan Masyarakat", "Ekonomi"] },
  { id: "its", name: "Institut Teknologi Sepuluh Nopember", abbr: "ITS", province: "Jawa Timur", indexedDocs: 298500, status: "Terverifikasi", topFaculties: ["Teknik Elektro", "Informatika", "Desain Produk"] },
  { id: "unri", name: "Universitas Riau", abbr: "UNRI", province: "Riau", indexedDocs: 121800, status: "Dalam Proses", topFaculties: ["Pertanian", "Hukum", "Ekonomi"] },
  { id: "unhas", name: "Universitas Hasanuddin", abbr: "UNHAS", province: "Sulawesi Selatan", indexedDocs: 187400, status: "Terverifikasi", topFaculties: ["Kelautan", "Kedokteran", "Pertanian"] },
  { id: "usu", name: "Universitas Sumatera Utara", abbr: "USU", province: "Sumatera Utara", indexedDocs: 165300, status: "Dalam Proses", topFaculties: ["Kedokteran", "Teknik", "Hukum"] },
];

export const documents = [
  { id: "doc-1", title: "Implementasi Framework iRDR untuk Deteksi Research Gap pada Literatur Kecerdasan Buatan", authors: ["Ayu Ramadhani", "Bagas Wicaksono"], universityId: "ui", university: "Universitas Indonesia", faculty: "Ilmu Komputer", program: "S1 Ilmu Komputer", degree: "S1", year: 2025, language: "Indonesia", repository: "UIRepository", disciplineId: "komputer", keywords: ["Kecerdasan Buatan", "Research Gap", "NLP"], abstract: "Penelitian ini mengembangkan pendekatan berbasis framework iRDR untuk mengidentifikasi celah penelitian pada korpus artikel kecerdasan buatan berbahasa Indonesia, menggabungkan pemodelan topik dengan analisis sitasi.", doi: "10.1234/ui.2025.0142" },
  { id: "doc-2", title: "Analisis Manajemen Pendidikan Inklusif di Sekolah Dasar Daerah 3T", authors: ["Citra Lestari"], universityId: "ugm", university: "Universitas Gadjah Mada", faculty: "Ilmu Pendidikan", program: "S2 Manajemen Pendidikan", degree: "S2", year: 2024, language: "Indonesia", repository: "UGM-ETD", disciplineId: "pendidikan", keywords: ["Pendidikan Inklusif", "Manajemen Pendidikan", "Daerah 3T"], abstract: "Studi kualitatif mengenai praktik manajemen pendidikan inklusif di sekolah dasar pada wilayah tertinggal, terdepan, dan terluar, dengan fokus pada strategi alokasi sumber daya dan pelatihan guru.", doi: "10.1234/ugm.2024.0871" },
  { id: "doc-3", title: "Optimasi Struktur Rangka Baja Tahan Gempa Menggunakan Algoritma Genetika", authors: ["Dimas Prakoso", "Fahmi Aulia", "Gilang Ramadhan"], universityId: "itb", university: "Institut Teknologi Bandung", faculty: "Teknik Sipil", program: "S1 Teknik Sipil", degree: "S1", year: 2025, language: "Indonesia", repository: "ITB Repository", disciplineId: "teknik", keywords: ["Rekayasa Struktur", "Algoritma Genetika", "Ketahanan Gempa"], abstract: "Penelitian mengoptimalkan dimensi profil baja pada rangka gedung bertingkat menggunakan algoritma genetika untuk memenuhi kriteria ketahanan gempa dengan biaya material minimum.", doi: "10.1234/itb.2025.0339" },
  { id: "doc-4", title: "Energi Terbarukan dari Limbah Kelapa Sawit sebagai Sumber Bioenergi Berkelanjutan", authors: ["Hana Puspita"], universityId: "ipb", university: "IPB University", faculty: "Teknologi Pertanian", program: "S3 Ilmu Keteknikan Pertanian", degree: "S3", year: 2023, language: "Indonesia", repository: "IPB Scientific Repository", disciplineId: "pertanian", keywords: ["Energi Terbarukan", "Kelapa Sawit", "Bioenergi"], abstract: "Disertasi ini mengevaluasi potensi limbah tandan kosong kelapa sawit sebagai bahan baku bioenergi, mencakup analisis efisiensi konversi dan kelayakan ekonomi skala industri.", doi: "10.1234/ipb.2023.0055" },
  { id: "doc-5", title: "Novelty Analysis pada Kebijakan Perlindungan Data Pribadi di Sektor Fintech", authors: ["Indra Setiawan", "Julia Chandra"], universityId: "unpad", university: "Universitas Padjadjaran", faculty: "Hukum", program: "S2 Ilmu Hukum", degree: "S2", year: 2024, language: "Indonesia", repository: "UNPAD Repository", disciplineId: "hukum", keywords: ["Perlindungan Data", "Fintech", "Kebijakan Publik"], abstract: "Kajian normatif terhadap kesenjangan regulasi perlindungan data pribadi pada penyelenggara layanan keuangan digital, disertai analisis novelty terhadap penelitian terdahulu.", doi: "10.1234/unpad.2024.0212" },
  { id: "doc-6", title: "Kesehatan Masyarakat Perkotaan: Determinan Stunting pada Balita di Wilayah Padat Penduduk", authors: ["Kirana Wulandari"], universityId: "unair", university: "Universitas Airlangga", faculty: "Kesehatan Masyarakat", program: "S2 Kesehatan Masyarakat", degree: "S2", year: 2025, language: "Indonesia", repository: "UNAIR Repository", disciplineId: "kesehatan", keywords: ["Stunting", "Kesehatan Masyarakat", "Gizi Balita"], abstract: "Penelitian cross-sectional mengidentifikasi determinan sosial dan ekonomi stunting pada balita di kawasan padat penduduk perkotaan, dengan rekomendasi intervensi berbasis komunitas.", doi: "10.1234/unair.2025.0164" },
  { id: "doc-7", title: "Desain Komunikasi Visual untuk Literasi Digital Lansia", authors: ["Laras Anindya", "Made Wirawan"], universityId: "its", university: "Institut Teknologi Sepuluh Nopember", faculty: "Desain Produk", program: "S1 Desain Komunikasi Visual", degree: "S1", year: 2024, language: "Indonesia", repository: "ITS Repository", disciplineId: "desain", keywords: ["Desain Komunikasi Visual", "Literasi Digital", "Lansia"], abstract: "Perancangan sistem visual dan materi edukasi untuk meningkatkan literasi digital kelompok lansia, diuji melalui studi usability pada tiga kelompok komunitas.", doi: "10.1234/its.2024.0093" },
  { id: "doc-8", title: "Literature Review: Model Bisnis Platform Ekonomi Kolaboratif di Indonesia", authors: ["Nadia Safitri"], universityId: "ui", university: "Universitas Indonesia", faculty: "Ekonomi & Bisnis", program: "S1 Manajemen", degree: "S1", year: 2023, language: "Indonesia", repository: "UIRepository", disciplineId: "bisnis", keywords: ["Ekonomi Kolaboratif", "Model Bisnis", "Platform Digital"], abstract: "Tinjauan literatur sistematis terhadap 62 artikel mengenai model bisnis platform ekonomi kolaboratif, memetakan tren riset dan mengidentifikasi arah penelitian lanjutan.", doi: "10.1234/ui.2023.0301" },
  { id: "doc-9", title: "AI Research Assistant untuk Percepatan Tinjauan Pustaka Bidang Kesehatan", authors: ["Oscar Pratama", "Putri Ayudia"], universityId: "unhas", university: "Universitas Hasanuddin", faculty: "Ilmu Komputer", program: "S2 Ilmu Komputer", degree: "S2", year: 2025, language: "Inggris", repository: "UNHAS Repository", disciplineId: "komputer", keywords: ["AI Research Assistant", "Tinjauan Pustaka", "NLP Kesehatan"], abstract: "Pengembangan asisten riset berbasis large language model untuk mempercepat proses tinjauan pustaka pada domain kesehatan, dievaluasi terhadap tingkat akurasi ringkasan.", doi: "10.1234/unhas.2025.0027" },
  { id: "doc-10", title: "Arsitektur Hijau: Studi Kenyamanan Termal Bangunan Kampus Tropis", authors: ["Rangga Saputra"], universityId: "usu", university: "Universitas Sumatera Utara", faculty: "Teknik", program: "S1 Arsitektur", degree: "S1", year: 2024, language: "Indonesia", repository: "USU Repository", disciplineId: "arsitektur", keywords: ["Arsitektur Hijau", "Kenyamanan Termal", "Bangunan Tropis"], abstract: "Studi simulasi dan pengukuran lapangan terhadap kenyamanan termal ruang kelas pada bangunan kampus beriklim tropis lembap, dengan usulan strategi desain pasif.", doi: "10.1234/usu.2024.0186" },
];

export const researchCTAs = [
  { id: "s1", kicker: "Untuk Mahasiswa S1", title: "Sudah Menemukan Ide Judul Skripsi?", body: "Mulai susun penelitian S1 Anda dengan alur terbimbing dan audit trail yang menjaga keaslian proses penulisan Anda.", ctaLabel: "Mulai Penelitian S1", ctaHref: "https://risethibrida.com", ctaTarget: "_blank" },
  { id: "s2", kicker: "Untuk Mahasiswa S2", title: "Sudah Sinkron Rujukan Tesis Anda?", body: "Uji kelayakan proposal tesis S2 sebelum menemui dosen pembimbing — deteksi kesenjangan antara kerangka teori dan metode.", ctaLabel: "Scan Proposal Tesis", ctaHref: "https://risethibrida.com", ctaTarget: "_blank" },
  { id: "s3", kicker: "Untuk Peneliti & Dosen", title: "Siap Mengelevasi Topik ke Jurnal Internasional?", body: "Uji novelty dan kerapatan argumen naskah jurnal Scopus Anda sebelum submit, lengkap dengan pemeriksaan jurnal predator.", ctaLabel: "Validasi Naskah Jurnal", ctaHref: "https://risethibrida.com", ctaTarget: "_blank" },
  { id: "aff", kicker: "Kemitraan & Ambassador", title: "Punya Komunitas Peneliti di Kampus Anda?", body: "Rekomendasikan ResearchOS ke rekan sejawat dan raih komisi kemitraan berkelanjutan untuk setiap keberhasilan mereka.", ctaLabel: "Daftar Sebagai Partner", ctaHref: "mailto:hello@risethibrida.com?subject=Daftar%20Affiliate%20iRDR%20Scholar", ctaTarget: "_self" },
];
export function getCTA(id) { return researchCTAs.find(c => c.id === id) || researchCTAs[0]; }

export function getDocument(id) { return documents.find(d => d.id === id); }
export function getUniversity(id) { return universities.find(u => u.id === id); }
export function getDiscipline(id) { return disciplines.find(d => d.id === id); }
export function relatedDocuments(doc, limit = 3) {
  return documents.filter(d => d.id !== doc.id && (d.disciplineId === doc.disciplineId || d.universityId === doc.universityId)).slice(0, limit);
}
